# Bitcoin Core 31.1 — no conoce RDTS. Relaya/mina datos grandes (spam para Knots).
regtest=1
server=1
txindex=1
# permitir datacarrier grande para que Core relaye/mine lo que Knots rechaza
datacarrier=1
datacarriersize=100000
acceptnonstdtxn=1

[regtest]
rpcuser=bip110
rpcpassword=bip110pass
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
rpcport=18443
port=18444
whitelist=noban,mempool,relay@10.0.0.0/8
whitelist=noban,mempool,relay@172.16.0.0/12
listen=1
discover=0
fallbackfee=0.0002
dnsseed=0
