# Bitcoin Knots — nodo regtest que APLICA el softfork BIP-110 / RDTS.
regtest=1
server=1
txindex=1
# --- RDTS / BIP-110 ---
consensusrules=rdts

[regtest]
rpcuser=bip110
rpcpassword=bip110pass
rpcbind=0.0.0.0
rpcallowip=0.0.0.0/0
rpcport=18443
port=18444
# no banear peers de la subred docker (el split debe ser por consenso, no por ban)
whitelist=noban,mempool,relay@10.0.0.0/8
whitelist=noban,mempool,relay@172.16.0.0/12
listen=1
discover=0
fallbackfee=0.0002
dnsseed=0
